Setting up code coverage (#95)
* implemented coverage reporting and moved clang compiler options to a dedicated cmake file

* added coverage run in linux job

* added missing llvm dependency on the runner

* fixed link option on ubuntu

* fixed clang debug flags

* removed verbose print

* removed verbose print and display markdown report in github action summary

* forgot to replace variable after testing

* removed unnecessary section

* renamed html coverage report target

* renamed the dependency

* refactored cmake code to make it more readable (and simple)

* added documentation

* refactored to cmake macros since it's more relevant in such script

diff --git a/.github/workflows/linux_build_test.yaml b/.github/workflows/linux_build_test.yaml
--- a/.github/workflows/linux_build_test.yaml
+++ b/.github/workflows/linux_build_test.yaml
@@ -16,10 +16,10 @@ jobs:
     strategy:
       matrix:
         include:
-          - name: clang_release
-            configure_preset: clang_release
-            build_preset: clang_release
-            test_preset: quick-validation-clang-release
+          - name: clang_debug
+            configure_preset: clang_debug
+            build_preset: clang_debug
+            test_preset: quick-validation-clang-debug
 
     steps:
       - uses: actions/checkout@v4
@@ -31,6 +31,7 @@ jobs:
             build-essential \
             clang \
             clang-tidy \
+            llvm \
             gcc \
             g++ \
             git \
@@ -133,3 +134,30 @@ jobs:
           fi
 
           exit $TEST_EXIT_CODE
+
+      - name: Coverage (${{ matrix.test_preset }})
+        shell: bash
+        run: |
+          set +e
+          cmake --build --preset ${{ matrix.build_preset }} --target coverage-markdown 2>&1 | tee coverage_gh_summary.txt
+          COV_EXIT_CODE=${PIPESTATUS[0]}  # Capture CMake exit code, not tee
+          set -e
+
+          COVERAGE_FILE=$(grep -Po "GitHub Markdown summary written to: \K.*" coverage_gh_summary.txt)
+          # -P: Uses Perl-style regex.
+          # -o: Only outputs the matched part (not the whole line).
+          # \K: Tells the engine to match the string but ignore it in the final output.
+          # .*: Matches the rest of the line (the path)
+
+          if [ $COV_EXIT_CODE -eq 0 ]; then
+            echo "<details><summary>🟢 Coverage Results (click to expand)</summary>" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "## 🔴 Coverage Results" >> $GITHUB_STEP_SUMMARY
+          fi
+          echo '' >> $GITHUB_STEP_SUMMARY
+          cat $COVERAGE_FILE >> $GITHUB_STEP_SUMMARY
+          if [ $COV_EXIT_CODE -eq 0 ]; then
+            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          fi
+
+          exit $COV_EXIT_CODE
