Adding coverage badge and link html report (#97)
* added logic to build shieldsio badge from existing code

* separated cmake functions in common between markdown and shieldsio parsing

* added message in html target to tell the build directory (easy to retrieve in github action)

* added code to generate reports and push them to gh pages

* updated readme to reference the badge

* added debug info

* fixed exit too early in coverage steps

* fixed syntax error while exporting to github output

* added missing write contents

* added badges to the readme

* made html coverage generation and badge export to github pages only happen on merge on branch main

* added shields io cmake script usage example

* forgot to make this step occurr only when triggered by main branch

diff --git a/.github/workflows/linux_build_test.yaml b/.github/workflows/linux_build_test.yaml
--- a/.github/workflows/linux_build_test.yaml
+++ b/.github/workflows/linux_build_test.yaml
@@ -13,6 +13,11 @@ jobs:
     runs-on: ubuntu-latest
     name: ${{ matrix.test_preset }}
 
+    permissions:
+      # coverage artefacts export requires write priviledges
+      # (html report and shields.io badge)
+      contents: write
+
     strategy:
       matrix:
         include:
@@ -135,7 +140,7 @@ jobs:
 
           exit $TEST_EXIT_CODE
 
-      - name: Coverage (${{ matrix.test_preset }})
+      - name: Generate markdown coverage report (${{ matrix.test_preset }})
         shell: bash
         run: |
           set +e
@@ -161,3 +166,50 @@ jobs:
           fi
 
           exit $COV_EXIT_CODE
+
+      - name: Generate html coverage report (${{ matrix.test_preset }})
+        if: github.ref_name == 'main'
+        id: htmlcov
+        shell: bash
+        run: |
+          set +e
+          cmake --build --preset ${{ matrix.build_preset }} --target coverage-html 2>&1 | tee coverage_html_summary.txt
+          COV_EXIT_CODE=${PIPESTATUS[0]}  # Capture CMake exit code, not tee
+          set -e
+
+          HTML_COV_DIR=$(grep -Po "HTML coverage directory: \K.*" coverage_html_summary.txt)
+          echo "HTML_COV_DIR=$HTML_COV_DIR" >> "$GITHUB_OUTPUT"
+
+          exit $COV_EXIT_CODE
+
+      - name: Generate shields.io badge (${{ matrix.test_preset }})
+        if: github.ref_name == 'main'
+        id: shieldsio
+        shell: bash
+        run: |
+          set +e
+          cmake --build --preset ${{ matrix.build_preset }} --target coverage-shieldsio 2>&1 | tee coverage_shieldsio_summary.txt
+          COV_EXIT_CODE=${PIPESTATUS[0]}  # Capture CMake exit code, not tee
+          set -e
+
+          SHIELDSIO_BADGE_FILE=$(grep -Po "Shields.io badge written to: \K.*" coverage_shieldsio_summary.txt)
+          echo "SHIELDSIO_BADGE_FILE=$SHIELDSIO_BADGE_FILE" >> "$GITHUB_OUTPUT"
+
+          exit $COV_EXIT_CODE
+
+      - name: Prepare files
+        if: github.ref_name == 'main'
+        shell: bash
+        run: |
+          mkdir -p out/
+          cp -r "${{ steps.htmlcov.outputs.HTML_COV_DIR }}" out/
+          cp "${{ steps.shieldsio.outputs.SHIELDSIO_BADGE_FILE }}" out/
+
+      - name: Publish coverage badge and report to gh-pages
+        if: github.ref_name == 'main'
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_branch: gh-pages
+          publish_dir: out
+          keep_files: true
